settings:
  title: 'Status Page'
  url: 'https://status-page.eidam.dev' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: www-cmclient-pl # unique identifier
    name: cmclient.pl
    description: 'You write code. They handle the rest.' # default=empty
    url: 'https://cmclient.pl' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true

  - id: launcher-cm-pack-pl
    name: www.cloudflare.com
    description: 'Built for anything connected to the Internet.'
    url: 'https://launcher.cm-pack.pl'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true

  - id: status-cmclient-pl
    name: CM status
    url: 'https://status.cmclient.pl'
    method: GET
    expectStatus: 200
